jenkins:
  systemMessage: "\n\nDemo setup for Jenkins Configuration as Code plugin......\n\n"

  numExecutors: 1
  mode: NORMAL
  scmCheckoutRetryCount: 3
  labelString: "master-label"  

  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Jenkins administrators"
            permissions:
              - "Overall/Administer"
            assignments:
              - "admin"
          - name: "readonly"
            description: "Read-only users"
            permissions:
              - "Overall/Read"
              - "Job/Read"
              #- "Job/Build"
            assignments:
              - "authenticated"
        items:
          - name: "FolderA"
            description: "Jobs in Folder A, but not the folder itself"
            pattern: "FolderA/.*"
            permissions:
              - "Job/Configure"
              - "Job/Build"
              - "Job/Delete"
            assignments:
              - "user1"
              - "user2"
          - name: "job1"
            description: "Jobs in Folder A, but not the folder itself"
            pattern: "job1"
            permissions:
              - "Job/Configure"
              - "Job/Build"
              - "Job/Delete"
            assignments:
              - "user1"
              - "user2"
          - name: "FolderB"
            description: "Jobs in Folder B, but not the folder itself"
            pattern: "FolderB.*"
            permissions:
              - "Job/Configure"
              - "Job/Build"
            assignments:
              - "user2"
        agents:
          - name: "Agent1"
            description: "Agent 1"
            pattern: "agent1"
            permissions:
              - "Agent/Build"
            assignments:
              - "user1"

  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "admin"
        - id: "user1"
          password: "user1"
        - id: "user2"
          password: "user2"
        - id: "user_hashed"
          # password is password
          password: "#jbcrypt:$2a$10$3bnAsorIxhl9kTYvNHa2hOJQwPzwT4bv9Vs.9KdXkh9ySANjJKm5u"
        
  crumbIssuer: "standard"

  remotingSecurity:
    enabled: true    

credentials:
  system:
    domainCredentials:
      - credentials:
        - usernamePassword:
            scope:    GLOBAL
            id:       oki-user
            username: oki
            password: oki
            description: github username/password  
        - usernamePassword:
            scope:    GLOBAL
            id:       user1
            username: user1
            password: user1
            description: user1 username/password  
        - usernamePassword:
            scope:    GLOBAL
            id:       user2
            username: user2
            password: user2
            description: user2 username/password  

tool:
  git:
    installations:
      - name: Default
        home: "git"

jobs:
  - script: >
      job('testJob1') {
          scm {
              git('git://github.com/quidryan/aws-sdk-test.git')
          }
          triggers {
              scm('H/15 * * * *')
          }
          steps {
              maven('-e clean test')
          }
      }

